#!/usr/bin/env bash

set -x

if ! [[ -z "$USE_COMPILER" ]]; then
  USE_COMPILER_ENV="-e CRYSTAL_PATH=/opt/crystal/src"
fi

[[ -z "$ARCH" ]] && ARCH=$(arch)
docker run \
    -it \
    --rm \
    -u $(id -u) \
    -v $(readlink -f ../crystal/):/mnt \
    -v $(pwd):/code \
    -w /code \
    -e LIBRARY_PATH="/opt/crystal/embedded/lib/" \
    $USE_COMPILER_ENV \
    "jhass/crystal-build-$ARCH" \
    "$@"
